routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PageController@index');
Route::get('{catid}/teemad', ['uses' =>'PageController@viewThemes']);
Route::get('teema/{id}', ['uses' => 'PageController@openTheme']);
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::resource('tests', 'TestsController');
    Route::resource('users', 'UserController');
    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');
});
Route::delete('tests/mass_destroy', 'TestsController@massDestroy')->name('tests.mass_destroy');
Route::get('/home', 'HomeController@index')->name('home');

//Routes for tests
Route::post('teema/{id}/getTests', ['uses' => 'PageController@getTests']);
Route::post('teema/{id}/getResults', ['uses' => 'PageController@getResults']);

//Routes for calculators
Route::post('teema/{id}/calc/triangle/', ['uses' => 'PageController@triangleCalc']);
Route::post('teema/{id}/calc/square/', ['uses' => 'PageController@squareCalc']);
Route::post('teema/{id}/calc/rectangle/', ['uses' => 'PageController@rectangleCalc']);
Route::post('teema/{id}/calc/rhombus/', ['uses' => 'PageController@rhombusCalc']);
Route::post('teema/{id}/calc/parallelogram/', ['uses' => 'PageController@parallelogramCalc']);
Route::post('teema/{id}/calc/trapesium/', ['uses' => 'PageController@trapesiumCalc']);
Route::post('teema/{id}/calc/cube/', ['uses' => 'PageController@cubeCalc']);
Route::post('teema/{id}/calc/rectangular/', ['uses' => 'PageController@rectangularCalc']);
Route::post('teema/{id}/calc/uprightPrism/', ['uses' => 'PageController@uprightPrismCalc']);
Route::post('teema/{id}/calc/paralleloPrism/', ['uses' => 'PageController@paralleloPrismCalc']);


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');



// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use DB;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::paginate(10);
        return view('users.index', compact('users'))->with('users', $user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::findorFail($id);

        return view('users.edit', compact('user'))->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user = User::findOrFail($id);
        $user->update($request->all());
        return redirect()->route('users.index')->with(['message' => 'Kasutaja andmed uuendatud']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::findorFail($id);
        $user->delete();
        return redirect()->route('users.index')->with(['message'=>'Kasutaja on kustutatud']);
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Muuda kasutajat</div>

                    <div class="panel-body">
                        @if ($errors->count() > 0)
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                        <form action="{{ route('users.update', $user->id) }}" method="post">
                            <input type="hidden" name="_method" value="PUT">
                            {{ csrf_field() }}
                            @if(strtoupper($user->name)=='TEST' || strtoupper($user->name)=='TESTS' || strtoupper($user->name)=='ADMIN')
                            Nimi:
                            <br />
                            <input class="form-control" type="text" style="background-color: lightgray;" name="name" value="{{ $user->name }}" disabled/>
                            <br />
                            Email:
                            <br />
                            <input class="form-control" type="text" name="email" value="{{ $user->email }}" />
                            <br />
                            @else
                                Nimi:
                                <br />
                                <input class="form-control" type="text" name="name" value="{{ $user->name }}"/>
                                <br />
                                Email:
                                <br />
                                <input class="form-control" type="text" name="email" value="{{ $user->email }}" />
                                <br />
                            @endif
                            <input class="form-control" type="submit" value="Submit" class="btn btn-default" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                @if (session('message'))
                    <div class="alert alert-info">{{ session('message') }}</div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">Kasutajad</div>

                    <div class="panel-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Nimi</th>
                                <th>Email</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($users as $user)
                                @if(strtoupper($user->name)=='TEST' || strtoupper($user->name)=='ADMIN' )
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td><!-- Edit and Delete Buttons -->
                                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-default">Muuda</a>
                                    </td>
                                </tr>
                                @else
                                    <tr>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td><!-- Edit and Delete Buttons -->
                                            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-default">Muuda</a>
                                            <form action="{{ route('users.destroy', $user->id) }}" method="POST"
                                                  style="display: inline"
                                                  onsubmit="return confirm('Kas sa oled kindel?');">
                                                <input type="hidden" name="_method" value="DELETE">
                                                {{ csrf_field() }}
                                                <button class="btn btn-danger">Kustuta</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endif
                            @empty
                                <tr>
                                    <td colspan="3">Ei leidnud ühtegi kirjet</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                        {{ $users->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection